CONTRACT_SPECS = {
    "Propane": {
        "ticker": "BAP",
        "contract_multiplier": 1000,
        "normalization": 0.42 * 100,
        "t_cost_abs": 0.0,
        "prompt_EOM_roll": {
            "style": "eom_ngl",
            "front_col": "F2",
            "next_col": "F3",
            "mid_col": "F2",
            "far_col": "F3",
            "group": "NGL",
        },
"q2_deferred_roll": {
            "style": "eom_ngl",
            "front_col": "F5",
            "next_col": "F6",
            "mid_col": "F5",
            "far_col": "F6",
            "group": "NGL",
        },
"q3_deferred_roll": {
            "style": "eom_ngl",
            "front_col": "F8",
            "next_col": "F9",
            "mid_col": "F8",
            "far_col": "F9",
            "group": "NGL",
        },
        "1yr_deferred_roll": {
            "style": "eom_ngl",
            "front_col": "F12",
            "next_col": "F13",
            "mid_col": "F12",
            "far_col": "F13",
            "group": "NGL",
        },
    },
    "Ethane": {
        "ticker": "CAP",
        "contract_multiplier": 1000,
        "normalization": 0.42 * 100,
        "t_cost_abs": 0.0,
        "prompt_EOM_roll": {
            "style": "eom_ngl",
            "front_col": "F2",
            "next_col": "F3",
            "mid_col": "F2",
            "far_col": "F3",
            "group": "NGL",
        },
"q2_deferred_roll": {
            "style": "eom_ngl",
            "front_col": "F5",
            "next_col": "F6",
            "mid_col": "F5",
            "far_col": "F6",
            "group": "NGL",
        },
"q3_deferred_roll": {
            "style": "eom_ngl",
            "front_col": "F8",
            "next_col": "F9",
            "mid_col": "F8",
            "far_col": "F9",
            "group": "NGL",
        },
        "1yr_deferred_roll": {
            "style": "eom_ngl",
            "front_col": "F12",
            "next_col": "F13",
            "mid_col": "F12",
            "far_col": "F13",
            "group": "NGL",
        },
    },
    "Butane": {
        "ticker": "DAE",
        "contract_multiplier": 1000,
        "normalization": 0.42 * 100,
        "t_cost_abs": 0.0,
        "prompt_EOM_roll": {
            "style": "eom_ngl",
            "front_col": "F2",
            "next_col": "F3",
            "mid_col": "F2",
            "far_col": "F3",
            "group": "NGL",
        },
"q2_deferred_roll": {
            "style": "eom_ngl",
            "front_col": "F5",
            "next_col": "F6",
            "mid_col": "F5",
            "far_col": "F6",
            "group": "NGL",
        },
"q3_deferred_roll": {
            "style": "eom_ngl",
            "front_col": "F8",
            "next_col": "F9",
            "mid_col": "F8",
            "far_col": "F9",
            "group": "NGL",
        },
        "1yr_deferred_roll": {
            "style": "eom_ngl",
            "front_col": "F12",
            "next_col": "F13",
            "mid_col": "F12",
            "far_col": "F13",
            "group": "NGL",
        },
    },
    "WTI Houston": {
        "ticker": "HRT",
        "contract_multiplier": 1000,
        "normalization": 1.0,
        "t_cost_abs": 0.0,
    },
    "WTI": {
        "ticker": "CL",
        "contract_multiplier": 1000,
        "normalization": 1.0,
        "t_cost_abs": 0.0,
        "prompt_EOM_roll": {
            "style": "eom_mid",
            "front_col": "F2",
            "next_col": "F3",
            "group": "core_EOM_mid_F1F2",
        },
"q2_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F5",
            "next_col": "F6",
            "group": "core_EOM_mid_F1F2",
        },
"q3_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F8",
            "next_col": "F9",
            "group": "core_EOM_mid_F1F2",
        },
        "1yr_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F12",
            "next_col": "F13",
            "group": "core_EOM_mid_F1F2",
        },
    },
    "Brent": {
        "ticker": "CO",
        "contract_multiplier": 1000,
        "normalization": 1.0,
        "t_cost_abs": 0.0,
        "prompt_EOM_roll": {
            "style": "eom_dynamic",
            "front_col": "F1",
            "next_col": "F2",
            "third_col": "F3",
            "group": "Brent_dynamic",
        },
"q2_deferred_roll": {
            "style": "eom_dynamic",
            "front_col": "F4",
            "next_col": "F5",
            "third_col": "F6",
            "group": "Brent_dynamic",
        },
"q3_deferred_roll": {
            "style": "eom_dynamic",
            "front_col": "F7",
            "next_col": "F8",
            "third_col": "F9",
            "group": "Brent_dynamic",
        },
        "1yr_deferred_roll": {
            "style": "eom_dynamic",
            "front_col": "F12",
            "next_col": "F13",
            "third_col": "F14",
            "group": "Brent_dynamic",
        },
    },
    "Dubai": {
        "ticker": "DAT",
        "contract_multiplier": 1000,
        "normalization": 1.0,
        "t_cost_abs": 0.0,
        "prompt_EOM_roll": {
            "style": "eom_eom",
            "front_col": "F1",
            "next_col": "F2",
            "third_col": "F3",
            "group": "crude_EOM_eom",
        },
"q2_deferred_roll": {
            "style": "eom_eom",
            "front_col": "F4",
            "next_col": "F5",
            "third_col": "F6",
            "group": "crude_EOM_eom",
        },
"q3_deferred_roll": {
            "style": "eom_eom",
            "front_col": "F7",
            "next_col": "F8",
            "third_col": "F9",
            "group": "crude_EOM_eom",
        },
        "1yr_deferred_roll": {
            "style": "eom_eom",
            "front_col": "F12",
            "next_col": "F13",
            "third_col": "F14",
            "group": "crude_EOM_eom",
        },
    },
    "ULSD": {
        "ticker": "HO",
        "contract_multiplier": 1000,
        "normalization": 0.42,
        "t_cost_abs": 0.0,
        "prompt_EOM_roll": {
            "style": "eom_eom",
            "front_col": "F1",
            "next_col": "F2",
            "third_col": "F3",
            "group": "core_EOM_EOM",
        },
"q2_deferred_roll": {
            "style": "eom_eom",
            "front_col": "F4",
            "next_col": "F5",
            "third_col": "F6",
            "group": "core_EOM_EOM",
        },
"q3_deferred_roll": {
            "style": "eom_eom",
            "front_col": "F7",
            "next_col": "F8",
            "third_col": "F9",
            "group": "core_EOM_EOM",
        },
        "1yr_deferred_roll": {
            "style": "eom_eom",
            "front_col": "F12",
            "next_col": "F13",
            "third_col": "F14",
            "group": "core_EOM_EOM",
        },
    },
    "RBOB": {
        "ticker": "XB",
        "contract_multiplier": 1000,
        "normalization": 0.42,
        "t_cost_abs": 0.0,
        "prompt_EOM_roll": {
            "style": "eom_eom",
            "front_col": "F1",
            "next_col": "F2",
            "third_col": "F3",
            "group": "core_EOM_EOM",
        },
"q2_deferred_roll": {
            "style": "eom_eom",
            "front_col": "F4",
            "next_col": "F5",
            "third_col": "F6",
            "group": "core_EOM_EOM",
        },
"q3_deferred_roll": {
            "style": "eom_eom",
            "front_col": "F7",
            "next_col": "F8",
            "third_col": "F9",
            "group": "core_EOM_EOM",
        },
        "1yr_deferred_roll": {
            "style": "eom_eom",
            "front_col": "F12",
            "next_col": "F13",
            "third_col": "F14",
            "group": "core_EOM_EOM",
        },
    },
    "Gasoil": {
        "ticker": "QS",
        "contract_multiplier": 1000,
        "normalization": 1.0 / 7.45,
        "t_cost_abs": 0.0,
        "prompt_EOM_roll": {
            "style": "eom_mid",
            "front_col": "F1",
            "next_col": "F2",
            "group": "core_EOM_mid_F1F2",
        },
"q2_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F4",
            "next_col": "F5",
            "group": "core_EOM_mid_F1F2",
        },
"q3_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F7",
            "next_col": "F8",
            "group": "core_EOM_mid_F1F2",
        },
        "1yr_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F12",
            "next_col": "F13",
            "group": "core_EOM_mid_F1F2",
        },
    },
    "Natgas": {
        "ticker": "NG",
        "contract_multiplier": 1000,
        "normalization": 5.8,
        "t_cost_abs": 0.0,
        "prompt_EOM_roll": {
            "style": "eom_mid",
            "front_col": "F1",
            "next_col": "F2",
            "group": "core_EOM_mid_F1F2",
        },
"q2_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F4",
            "next_col": "F5",
            "group": "core_EOM_mid_F1F2",
        },
"q3_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F7",
            "next_col": "F8",
            "group": "core_EOM_mid_F1F2",
        },
        "1yr_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F12",
            "next_col": "F13",
            "group": "core_EOM_mid_F1F2",
        },
    },
    # ── Crude grades ─────────────────────────────────────────────────────────
    "HTT": {
        "ticker": "HRT",
        "contract_multiplier": 1000,
        "normalization": 1.0,
        "t_cost_abs": 0.0,
        "prompt_EOM_roll": {
            "style": "eom_mid",
            "front_col": "F2",
            "next_col": "F3",
            "group": "crude_grade_EOM_mid",
        },
"q2_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F5",
            "next_col": "F6",
            "group": "crude_grade_EOM_mid",
        },
"q3_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F8",
            "next_col": "F9",
            "group": "crude_grade_EOM_mid",
        },
        "1yr_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F12",
            "next_col": "F13",
            "group": "crude_grade_EOM_mid",
        },
    },
    "WTI Midland": {
        "ticker": "HWT",
        "contract_multiplier": 1000,
        "normalization": 1.0,
        "t_cost_abs": 0.0,
        "prompt_EOM_roll": {
            "style": "eom_mid",
            "front_col": "F2",
            "next_col": "F3",
            "group": "crude_grade_EOM_mid",
        },
"q2_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F5",
            "next_col": "F6",
            "group": "crude_grade_EOM_mid",
        },
"q3_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F8",
            "next_col": "F9",
            "group": "crude_grade_EOM_mid",
        },
        "1yr_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F12",
            "next_col": "F13",
            "group": "crude_grade_EOM_mid",
        },
    },
    "YV": {
        "ticker": "YVA",
        "contract_multiplier": 1000,
        "normalization": 1.0,
        "t_cost_abs": 0.0,
        "prompt_EOM_roll": {
            "style": "eom_mid",
            "front_col": "F1",
            "next_col": "F2",
            "group": "crude_grade_EOM_mid",
        },
"q2_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F4",
            "next_col": "F5",
            "group": "crude_grade_EOM_mid",
        },
"q3_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F7",
            "next_col": "F8",
            "group": "crude_grade_EOM_mid",
        },
        "1yr_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F12",
            "next_col": "F13",
            "group": "crude_grade_EOM_mid",
        },
    },
    "DAB": {
        "ticker": "JDA",
        "contract_multiplier": 1000,
        "normalization": 1.0,
        "t_cost_abs": 0.0,
        "prompt_EOM_roll": {
            "style": "eom_mid",
            "front_col": "F1",
            "next_col": "F2",
            "group": "crude_grade_EOM_mid",
        },
"q2_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F4",
            "next_col": "F5",
            "group": "crude_grade_EOM_mid",
        },
"q3_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F7",
            "next_col": "F8",
            "group": "crude_grade_EOM_mid",
        },
        "1yr_deferred_roll": {
            "style": "eom_mid",
            "front_col": "F12",
            "next_col": "F13",
            "group": "crude_grade_EOM_mid",
        },
    },
    # ── FFAs ─────────────────────────────────────────────────────────────────
    "TDL": {
        "ticker": "ZHE",
        "contract_multiplier": 1000,
        "normalization": 1.0,
        "t_cost_abs": 0.0,
        "prompt_EOM_roll": {
            "style": "eom_eom",
            "front_col": "F1",
            "next_col": "F2",
            "third_col": "F3",
            "group": "ffa_EOM_eom",
        },
"q2_deferred_roll": {
            "style": "eom_eom",
            "front_col": "F4",
            "next_col": "F5",
            "third_col": "F6",
            "group": "ffa_EOM_eom",
        },
"q3_deferred_roll": {
            "style": "eom_eom",
            "front_col": "F7",
            "next_col": "F8",
            "third_col": "F9",
            "group": "ffa_EOM_eom",
        },
        "1yr_deferred_roll": {
            "style": "eom_eom",
            "front_col": "F12",
            "next_col": "F13",
            "third_col": "F14",
            "group": "ffa_EOM_eom",
        },
    },
    "WDF": {
        "ticker": "QIA",
        "contract_multiplier": 1000,
        "normalization": 1.0,
        "t_cost_abs": 0.0,
        "prompt_EOM_roll": {
            "style": "eom_eom",
            "front_col": "F1",
            "next_col": "F2",
            "third_col": "F3",
            "group": "ffa_EOM_eom",
        },
"q2_deferred_roll": {
            "style": "eom_eom",
            "front_col": "F4",
            "next_col": "F5",
            "third_col": "F6",
            "group": "ffa_EOM_eom",
        },
"q3_deferred_roll": {
            "style": "eom_eom",
            "front_col": "F7",
            "next_col": "F8",
            "third_col": "F9",
            "group": "ffa_EOM_eom",
        },
        "1yr_deferred_roll": {
            "style": "eom_eom",
            "front_col": "F12",
            "next_col": "F13",
            "third_col": "F14",
            "group": "ffa_EOM_eom",
        },
    },
    # ── Other / not yet in panel ──────────────────────────────────────────────
    "Murban": {
        "ticker": "MUC",
        "contract_multiplier": 1000,
        "normalization": 1.0,
        "t_cost_abs": 0.0,
    },
    "Dutch TTF": {
        "ticker": "TSB",
        "contract_multiplier": 1000,
        "normalization": None,
        "t_cost_abs": 0.0,
    },
    "Fuel Oil": {
        "ticker": "AVR",
        "contract_multiplier": 1000,
        "normalization": 1.0,
        "t_cost_abs": 0.0,
    },
    "Gulf Jet Fuel": {
        "ticker": "GF",
        "contract_multiplier": 1000,
        "normalization": 0.42,
        "t_cost_abs": 0.0,
    },
    "Eurobob": {
        "ticker": "IHW",
        "contract_multiplier": 1000,
        "normalization": 1.0 / 7.45 * 10,
        "t_cost_abs": 0.0,
    },
    "Naphtha": {
        "ticker": "KI",
        "contract_multiplier": 1000,
        "normalization": 1.0 / 7.45 * 10,
        "t_cost_abs": 0.0,
    },
    "Japan Naphtha": {
        "ticker": "JAA",
        "contract_multiplier": 1000,
        "normalization": 1.0 / 7.45 * 10,
        "t_cost_abs": 0.0,
    },
}
